[tool.poetry]
name = "pygdrive2"
version = "0.1.0"
description = ""
authors = ["OhkuboSGMS <sinikake.gokiburi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pydrive2 = "^1.15.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
